Output server output to the console if it can't start
This is now important since if there are people who are missing slugs,
that will be reported on server startup, and we should be able to
distinguish this from other errors.

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -73,7 +73,12 @@ start_sinatra() {
     done
     # Make sure it's not an old one server still running:
     kill -0 "$SINATRA_PID" 2> /dev/null ||
-        { echo "Couldn't start Sinatra - is an old server running?"; exit 1; }
+        {
+            echo "Couldn't start Sinatra - is an old server running?"
+            echo "Server output was:"
+            cat "$BUILD_DIR/sinatra.log"
+            exit 1
+        }
     echo "done"
 }
 
